# Generated by Django 5.2.2 on 2025-08-08 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Email', models.EmailField(max_length=100, unique=True, verbose_name='email address')),
                ('Name', models.CharField(max_length=200)),
                ('Date_Of_Birth', models.DateField()),
                ('Mobile_no', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('pickup_datetime', models.DateTimeField(blank=True, null=True)),
                ('dropoff_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('city', models.CharField(default='Pune', editable=False, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('is_booked', models.BooleanField(default=False)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('dropoff_date', models.DateField()),
                ('dropoff_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driving_licence', models.FileField(upload_to='documents/%Y/%m/%d/driving_licence/')),
                ('residence_proof', models.FileField(upload_to='documents/%Y/%m/%d/residence_proof/')),
                ('pan_card', models.FileField(upload_to='documents/%Y/%m/%d/pan_card/')),
                ('aadhaar_card', models.FileField(upload_to='documents/%Y/%m/%d/aadhaar_card/')),
                ('payment_screenshot', models.ImageField(upload_to='documents/%Y/%m/%d/payment/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.car')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.AddField(
            model_name='registermodel',
            name='booked_car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_by_user', to='register.car'),
        ),
    ]
